import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#FBF8F6",
        "on-background": "#121d26",
        surface: "#FFFFFF",
        "surface-soft": "#FFF7F8",
        "surface-dim": "#d1dbe8",
        "surface-bright": "#f7f9ff",
        "surface-variant": "#d9e3f1",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#edf4ff",
        "surface-container": "#e4effd",
        "surface-container-high": "#dfe9f7",
        "surface-container-highest": "#d9e3f1",
        "on-surface": "#121d26",
        "on-surface-variant": "#534346",
        "inverse-surface": "#27313c",
        "inverse-on-surface": "#e8f2ff",
        outline: "#857276",
        "outline-variant": "#d8c1c5",
        "surface-tint": "#93455e",
        primary: {
          DEFAULT: "#823850",
          dark: "#7A334C",
          soft: "#F6E7EC",
          container: "#9f4f68",
          fixed: "#ffd9e1",
          "fixed-dim": "#ffb1c5",
        },
        "on-primary": "#ffffff",
        "on-primary-container": "#ffe2e7",
        "inverse-primary": "#ffb1c5",
        secondary: {
          DEFAULT: "#6d528e",
          container: "#dbbcff",
          fixed: "#eedbff",
          "fixed-dim": "#d9b9fd",
        },
        "on-secondary": "#ffffff",
        "on-secondary-container": "#624883",
        tertiary: {
          DEFAULT: "#1e5b3f",
          container: "#397456",
          fixed: "#b2f0cc",
          "fixed-dim": "#96d4b1",
        },
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#b8f7d2",
        "accent-soft": "#EFE9F7",
        "muted-text": "#6B7280",
        "subtle-text": "#9CA3AF",
        border: "#E6DDE2",
        warning: {
          DEFAULT: "#B7791F",
          soft: "#FFF4D8",
        },
        danger: {
          DEFAULT: "#B94A48",
          soft: "#FCE8E7",
        },
        success: {
          soft: "#E7F3EC",
        },
        error: {
          DEFAULT: "#ba1a1a",
          container: "#ffdad6",
        },
      },
      fontFamily: {
        sans: [
          "Inter",
          "Nunito Sans",
          "Source Sans 3",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "sans-serif",
        ],
        display: ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-editor": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        display: ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-editor": ["17px", { lineHeight: "1.8", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        unit: "4px",
        "container-max-form": "720px",
        "container-max-editor": "760px",
        "container-max-detail": "1024px",
        "container-max-dashboard": "1200px",
      },
      borderRadius: {
        sm: "8px",
        DEFAULT: "12px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        pill: "999px",
      },
      boxShadow: {
        sm: "0 1px 2px rgba(31, 41, 51, 0.05)",
        md: "0 8px 24px rgba(31, 41, 51, 0.08)",
        lg: "0 20px 48px rgba(31, 41, 51, 0.10)",
      },
      maxWidth: {
        form: "720px",
        editor: "760px",
        detail: "1024px",
        dashboard: "1200px",
      },
    },
  },
  plugins: [],
};

export default config;