// Generic base types
export type { ID, ISODateTime, JsonObject, JsonValue, Timestamps } from "./utils.js";

// Enums (const objects + union types)
export {
  AI_PROPOSAL_RISK_LEVELS,
  AI_PROPOSAL_SOURCES,
  AI_PROPOSAL_STATUSES,
  AI_PROPOSAL_TYPES,
  CHARACTER_ROLES,
  CHARACTER_SOURCES,
  CHARACTER_STATUSES,
  CREDIT_BALANCE_SOURCES,
  DEFAULT_LANGUAGES,
  DETECTED_SIGNAL_STATUSES,
  DETECTED_SIGNAL_TYPES,
  INTAKE_MESSAGE_ROLES,
  INTAKE_PHASES,
  INTAKE_SESSION_STATUSES,
  CHAPTER_BEAT_STATUSES,
  CHAPTER_EMOTIONS,
  CHAPTER_FUNCTIONS,
  CHAPTER_OUTLINE_STATUSES,
  CHAPTER_PROSE_SOURCES,
  CHAPTER_WRITING_STATUSES,
  CONTEXT_PACKET_BUILDER_VERSIONS,
  OPEN_LOOP_STATUSES,
  OUTLINE_PLAN_STATUSES,
  PLANNED_REVEAL_STATUSES,
  REVEAL_RISK_LEVELS,
  RETENTION_MARKER_TYPES,
  STORY_CONCEPT_SOURCES,
  STORY_CONCEPT_STATUSES,
  WORKFLOW_PHASES,
  FACT_CANON_STATUSES,
  FACT_CATEGORIES,
  FACT_IMPORTANCE,
  FACT_SOURCES,
  FOUNDATION_READINESS_LEVELS,
  FOUNDATION_STATUSES,
  HIGH_RISK_FACT_CATEGORIES,
  HIGH_RISK_FACT_CATEGORY_LIST,
  MOBILE_FORMAT_PREFERENCES,
  OUTPUT_STYLE_PREFERENCES,
  PROJECT_ENTRY_PATHS,
  PROJECT_STATUSES,
  READER_TARGETS,
  SPEECH_RULE_SOURCES,
  SPEECH_RULE_STATUSES,
  STORY_GENRES,
  SUBSCRIPTION_PLANS,
  TARGET_LENGTH_PLANS,
  USER_ROLES,
  WRITER_QUALITY_MODES,
  WRITING_SESSION_STATUSES,
} from "./enums.js";

export type {
  AiProposalRiskLevel,
  AiProposalSource,
  AiProposalStatus,
  AiProposalType,
  CharacterRole,
  CharacterSource,
  CharacterStatus,
  CreditBalanceSource,
  DefaultLanguage,
  DetectedSignalStatus,
  DetectedSignalType,
  IntakeMessageRole,
  IntakePhase,
  IntakeSessionStatus,
  ChapterBeatStatus,
  ChapterEmotion,
  ChapterFunction,
  ChapterOutlineStatus,
  ChapterProseSource,
  ChapterWritingStatus,
  ContextPacketBuilderVersion,
  OpenLoopStatus,
  OutlinePlanStatus,
  PlannedRevealStatus,
  RevealRiskLevel,
  RetentionMarkerType,
  StoryConceptSource,
  StoryConceptStatus,
  WorkflowPhase,
  FactCanonStatus,
  FactCategory,
  FactImportance,
  FactSource,
  FoundationReadinessLevel,
  FoundationStatus,
  HighRiskFactCategory,
  MobileFormatPreference,
  OutputStylePreference,
  ProjectEntryPath,
  ProjectStatus,
  ReaderTarget,
  SpeechRuleSource,
  SpeechRuleStatus,
  StoryGenre,
  SubscriptionPlan,
  TargetLengthPlan,
  UserRole,
  WriterQualityMode,
  WritingSessionStatus,
} from "./enums.js";

// Domain entities
export type {
  AiProposal,
  ChapterBeat,
  ChapterOutline,
  ChapterOutlineMarker,
  ChapterProseVersion,
  ChapterWritingState,
  Character,
  CharacterSafeSummary,
  ContextPacketLog,
  ForbiddenRevealEntry,
  OpenLoopSafeSummary,
  RevealSafeSummary,
  SpeechRuleSummary,
  WriterContextPacket,
  WriterContextPacketPreview,
  WritingSession,
  CharacterImportance,
  CreditBalance,
  DetectedSignal,
  Fact,
  FoundationReadinessCheck,
  IntakeMessage,
  IntakeSession,
  OpenLoop,
  OutlinePlan,
  PlannedReveal,
  Project,
  ProjectSettings,
  RelationshipSpeechRule,
  StoryConcept,
  StoryFoundation,
  UserProfile,
} from "./domain.js";

// API contracts
export type {
  ApiError,
  ApiResponse,
  ApiSuccess,
  PaginatedResponse,
  PaginationParams,
} from "./api.js";