// Generic base types
export type { ID, ISODateTime, JsonObject, JsonValue, Timestamps } from "./utils.js";

// Enums (const objects + union types)
export {
  AI_PROPOSAL_RISK_LEVELS,
  AI_PROPOSAL_SOURCES,
  AI_PROPOSAL_STATUSES,
  AI_PROPOSAL_TYPES,
  CHARACTER_ROLES,
  CHARACTER_SOURCES,
  CHARACTER_STATUSES,
  CREDIT_BALANCE_SOURCES,
  DEFAULT_LANGUAGES,
  FACT_CANON_STATUSES,
  FACT_CATEGORIES,
  FACT_IMPORTANCE,
  FACT_SOURCES,
  FOUNDATION_READINESS_LEVELS,
  FOUNDATION_STATUSES,
  HIGH_RISK_FACT_CATEGORIES,
  HIGH_RISK_FACT_CATEGORY_LIST,
  MOBILE_FORMAT_PREFERENCES,
  OUTPUT_STYLE_PREFERENCES,
  PROJECT_ENTRY_PATHS,
  PROJECT_STATUSES,
  READER_TARGETS,
  SPEECH_RULE_SOURCES,
  SPEECH_RULE_STATUSES,
  STORY_GENRES,
  SUBSCRIPTION_PLANS,
  TARGET_LENGTH_PLANS,
  USER_ROLES,
  WRITER_QUALITY_MODES,
} from "./enums.js";

export type {
  AiProposalRiskLevel,
  AiProposalSource,
  AiProposalStatus,
  AiProposalType,
  CharacterRole,
  CharacterSource,
  CharacterStatus,
  CreditBalanceSource,
  DefaultLanguage,
  FactCanonStatus,
  FactCategory,
  FactImportance,
  FactSource,
  FoundationReadinessLevel,
  FoundationStatus,
  HighRiskFactCategory,
  MobileFormatPreference,
  OutputStylePreference,
  ProjectEntryPath,
  ProjectStatus,
  ReaderTarget,
  SpeechRuleSource,
  SpeechRuleStatus,
  StoryGenre,
  SubscriptionPlan,
  TargetLengthPlan,
  UserRole,
  WriterQualityMode,
} from "./enums.js";

// Domain entities
export type {
  AiProposal,
  Character,
  CharacterImportance,
  CreditBalance,
  Fact,
  FoundationReadinessCheck,
  Project,
  ProjectSettings,
  RelationshipSpeechRule,
  StoryFoundation,
  UserProfile,
} from "./domain.js";

// API contracts
export type {
  ApiError,
  ApiResponse,
  ApiSuccess,
  PaginatedResponse,
  PaginationParams,
} from "./api.js";